### ISSUE TITLE
Unable to run POSH-SSH commands in some of my linux machines

### ISSUE THREAD

**Issue by viju3010** [darkoperator/Posh-SSH#545]
Hi Team, I am noticing the below issue when trying to list "Get-SSHTrustedHost". This happens one some of my jenkins slaves and I have multiple things including to reinstall the module. 

```
[root@vcavst-wdc-slave1 ~]# pwsh
PowerShell 7.3.3
```

```
PS /root> Get-SSHTrustedHost
MethodInvocationException: Exception calling "GetAllKeys" with "0" argument(s): "Additional text encountered after finished reading JSON content: }. Path '', line 33, position 0."
```

```
PS /root> Get-Module Posh-SSH

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Manifest   3.0.8                 Posh-SSH                            {Get-SCPItem, Get-SFTPItem, Get-SSHHostKey, Get-SSHJsonKnownHost…}
```

**Comment by viju3010** [comment]
My Code : 
```
# Remove trusted host keys to make host key validation succeeds
try{
    Write-host "Removing trusted host keys from the local host"
    $removeTrustedHosts = Get-SSHTrustedHost -Hostname $VC_ip | Remove-SSHTrustedHost -ErrorAction SilentlyContinue
#    Invoke-Expression "ssh-keygen -R $VC_ip"
    Write-host "Removed trusted host keys from the local host"
}
catch{
    Write-host "Could not remove trusted host keys"
    Write-Host $_.Exception|format-list -force
}
```

Error : 

```
Removing trusted host keys from the local host
PS>TerminatingError(Get-SSHTrustedHost): "Exception calling "GetAllKeys" with "0" argument(s): "Additional text encountered after finished reading JSON content: }. Path '', line 33, position 0.""
Could not remove trusted host keys
System.Management.Automation.MethodInvocationException: Exception calling "GetAllKeys" with "0" argument(s): "Additional text encountered after finished reading JSON content: }. Path '', line 33, position 0."
 ---> Newtonsoft.Json.JsonReaderException: Additional text encountered after finished reading JSON content: }. Path '', line 33, position 0.
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at SSH.Stores.JsonStore.LoadFromDisk()
   at SSH.Stores.JsonStore.OnGetKeys()
   at SSH.Stores.MemoryStore.get_HostKeys()
   at SSH.Stores.MemoryStore.GetAllKeys()
   at CallSite.Target(Closure, CallSite, Object)
   --- End of inner exception stack trace ---
```

**Comment by MVKozlov** [comment]
and what
>Additional text encountered after finished reading JSON content

you see in `$env:USERPROFILE\.poshssh\hosts.json` ?

> line 33, position 0.""

**Comment by viju3010** [comment]
```[root@vcavst-wdc-slave1 ~]# cat /root/.poshssh/hosts.json
{
  "Keys": {
    "xx.xxx.50.14": {
      "HostKeyName": "ecdsa-sha2-nistp256",
      "Fingerprint": "da:26:52:6d:14:51:2:f2:70:8d:f7:87:fd:72:a1:c8"
    },
    "xx.xxx.50.170": {
      "HostKeyName": "ecdsa-sha2-nistp256",
      "Fingerprint": "e:8a:9d:75:64:91:e:d8:53:c5:b8:d3:fd:75:9c:3e"
    },
    "xx.xxx.50.61": {
      "HostKeyName": "ecdsa-sha2-nistp256",
      "Fingerprint": "2a:45:66:33:80:6:d0:d:c6:96:e3:9d:db:3d:98:48"
    },
    "xx.xxx.50.97": {
      "HostKeyName": "ecdsa-sha2-nistp256",
      "Fingerprint": "5:a5:7e:16:7f:e1:43:9b:5e:4f:6:ee:7e:2a:e6:7"
    },
    "xx.xxx.50.232": {
      "HostKeyName": "ecdsa-sha2-nistp256",
      "Fingerprint": "85:2b:f:3f:d4:cf:e6:8f:32:94:b3:23:9b:2f:45:b8"
    },
    "xx.xxx.50.10": {
      "HostKeyName": "ecdsa-sha2-nistp256",
      "Fingerprint": "8c:96:77:25:45:d4:e:6e:dc:8b:19:fc:37:6c:24:c8"
    },
    "xx.xxx.50.37": {
      "HostKeyName": "ecdsa-sha2-nistp256",
      "Fingerprint": "e2:ed:8b:83:3e:10:80:11:56:12:a3:e3:f0:47:6:1a"
    }
  }
}
}
```
Looks like an additional bracket at the end

**Comment by viju3010** [comment]
After removing the } in the end, the commands are working. Thank you !
